- name: Create AWS EC2 Instance
  hosts: localhost
  gather_facts: False
  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "public-compute-instance"
      key_name: "teste"
      vpc_subnet_id: subnet-0afbadb57f78ba020
      instance_type: t2.small
      security_group: sg-0192335cc675e23b3
      network:
        assign_public_ip: true
      image_id: ami-026ebd4cfe2c043b2 // rhell
      tags:
        Environment: Testing
