- name: Instala pacotes 
  hosts: all
  tasks:
  - name: Instala Apache
    ansible.builtin.yum:
      name: httpd
      state: latest
  - name: Instala PHP
    ansible.builtin.yum:
      name: php
      state: latest  
