- name: Instala pacotes 
  hosts: all
  tasks:
  - name: Cria diretorio temporario
    ansible.builtin.file:
      path: /tmp/phpapp2
      state: directory
      mode: '0755'
  - name: Clona diretorio app
    ansible.builtin.git:
      repo: https://github.com/LucianoRed/phpapp2.git
      dest: /tmp/phpapp2/
      single_branch: yes
      version: main
  - name: Copia para docroot
    ansible.posix.synchronize:
      src: /tmp/phpapp2/
      dest: /var/www/html      
    delegate_to: "{{ inventory_hostname }}"      
      
