- name: Instala pacotes 
  hosts: all
  tasks:
  - name: Instala Apache
    ansible.builtin.yum:
      name: httpd
      state: latest
  - name: Instala PHP
    ansible.builtin.yum:
      name: php
      state: latest  
  - name: Instala Git
    ansible.builtin.yum:
      name: git
      state: latest        
  - name: Inicia e Habilita HTTP
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true
      
