- name: Cria aplicacao no Openshift
  hosts: localhost
  tasks:
  - name: Create a k8s namespace
    community.okd.k8s:
      api_key: "{{ api_key }}"
      host: "{{ host_ocp }}"
      name: redhatday
      api_version: v1
      kind: Namespace
      state: present
