- name: Cria uma instancia na AWS
  hosts: localhost
  gather_facts: False
  tasks:
  - name: Inicia uma instancia com IP Publico
    amazon.aws.ec2_instance:
      name: "{{ nome_instancia }}"
      key_name: "teste"
      region: us-east-1
      vpc_subnet_id: subnet-0afbadb57f78ba020
      instance_type: t2.small
      security_group: sg-0192335cc675e23b3
      network:
        assign_public_ip: true
      image_id: ami-026ebd4cfe2c043b2
      tags:
        Environment: RedHatDay
    register: ec2_instance

  - name: Registra ip publico
    set_fact:
        public_ip: "{{ ec2_instance.instances[0].public_ip }}"

  - name: Espera SSH habilitado para seguir
    wait_for:
        host: "{{ public_ip }}"
        port: 22
        delay: 5
        timeout: 300
        state: started

  - name: Registra variavel global
    ansible.builtin.set_stats:
      data:
        public_ip_global: "{{ public_ip }}"     
